### PR TITLE
fix: retrieve token for each package's registry ala `cargo:token`

### LINKED ISSUE #1659: Inconsistent behaviour using release-plz with private, authenticated registries
## Bug description

I am using cargo with a private registry (kellnr.io, sparse index) which is read and write protected.

Credentials are needed for every operation on it.
Cargo takes them from the file `~/.cargo/credentials.toml` which looks like:

```toml
# private registry, private crates
[registries.myregistry]
token = "myregistry-token-here"

# private registry, crates-io cache
[registries.myregistry-cratesio]
token = "myregistry-token-here"
```

If you want to read up more on configuration see: <https://kellnr.io/documentation#configure-cargo> and <https://doc.rust-lang.org/cargo/reference/registry-authentication.html>

---

When running `release-plz release-pr --backend gitlab --git-token "mygit-token-here" --registry myregistry` everything works fine:

```log
  2024-09-06T07:33:04.355824Z  INFO  downloading packages from cargo registry
    in download with self=PackageDownloader { packages: ["mypackage"], directory: "/tmp/.tmpOkXTot", registry: Some("myregistry"), cargo_cwd: None }
    in next_versions
    in update
    in release_pr

note: Cloning into "/tmp/.tmpOkXTot"
    Updating `myregistry` index
  Credential cargo:wincred get myregistry
  Credential cargo:token get myregistry
note: Downloading mypackage 0.6.1
  2024-09-06T07:33:04.746360Z  INFO  mypackage: next version is 0.6.2
    in packages_to_update
    in next_versions
    in update
    in release_pr

  2024-09-06T07:33:06.022338Z  INFO  updated pr https://git.myhost.int/bla/mypackage/-/merge_requests/14
    in release_pr
```

---

however running `release-plz release --backend gitlab --git-token "mygit-token-here" --registry myregistry` does not work when there is an actual release waiting to be released:

```log
  2024-09-06T09:15:57.652040Z  INFO  release-plz config file not found, using default configuration

  2024-09-06T09:15:57.652166Z DEBUG  initializing directory "/home/myuser/Projects/mypackage"
    in new

  2024-09-06T09:15:57.654658Z DEBUG  Processing: "git@git.myhost.int:bla/mypackage.git"

  2024-09-06T09:15:57.656102Z DEBUG  Scheme::SSH match for normalization

  2024-09-06T09:15:57.656119Z DEBUG  Normalizing ssh url: ["git@git.myhost.int", "bla/mypackage.git"]

  2024-09-06T09:15:57.656128Z DEBUG  Processing: "ssh://git@git.myhost.int/bla/mypackage.git"

  2024-09-06T09:15:57.656649Z DEBUG  The urlpath: "bla/mypackage.git"

  2024-09-06T09:15:57.656661Z DEBUG  rsplit results for metadata: ["mypackage.git", "bla"]

  2024-09-06T09:15:57.656751Z DEBUG  GitLab API URL: https://git.myhost.int/api/v4/projects/bla%2Fmypackage

  2024-09-06T09:15:57.656836Z DEBUG  manifest_dir: "/home/myuser/Projects/tests/mypackage"
    in release

  2024-09-06T09:15:57.657887Z DEBUG  project_root: "/home/myuser/Projects/tests/mypackage"
    in release

  2024-09-06T09:15:57.658060Z DEBUG  initializing directory "/home/myuser/Projects/tests/mypackage"
    in new
    in release

  2024-09-06T09:15:57.663288Z DEBUG  Release order: ["mypackage"]
    in release

  2024-09-06T09:15:57.670757Z DEBUG  starting new connection: https://crates.myregistry.int/
    in release

  2024-09-06T09:15:57.670913Z DEBUG  resolving host="crates.myregistry.int"

  2024-09-06T09:15:57.676870Z DEBUG  connecting to x.x.x.x:443
    in release

  2024-09-06T09:15:57.677254Z DEBUG  connected to x.x.x.x:443
    in release

  2024-09-06T09:15:57.679073Z DEBUG  binding client connection
    in release

  2024-09-06T09:15:57.679121Z DEBUG  client connection bound
    in release

  2024-09-06T09:15:57.679147Z DEBUG  send, frame: Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384, max_header_list_size: 16384 }
    in release

  2024-09-06T09:15:57.679281Z DEBUG  pooling idle connection for ("https", crates.myregistry.int)
    in release

  2024-09-06T09:15:57.679380Z DEBUG  received, frame: Settings { flags: (0x0), max_concurrent_streams: 100 }
    in Connection with peer=Client
    in release

  2024-09-06T09:15:57.679405Z DEBUG  send, frame: Settings { flags: (0x1: ACK) }
    in Connection with peer=Client
    in release

  2024-09-06T09:15:57.679422Z DEBUG  received, frame: WindowUpdate { stream_id: StreamId(0), size_increment: 2147418112 }
    in Connection with peer=Client
    in release

  2024-09-06T09:15:57.679443Z DEBUG  send, frame: WindowUpdate { stream_id: StreamId(0), size_increment: 5177345 }
    in Connection with peer=Client
    in release

  2024-09-06T09:15:57.679462Z DEBUG  send, frame: Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }
    in Connection with peer=Client
    in release

  2024-09-06T09:15:57.679815Z DEBUG  received, frame: Settings { flags: (0x1: ACK) }
    in Connection with peer=Client
    in release

  2024-09-06T09:15:57.679836Z DEBUG  received settings ACK; applying Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384, max_header_list_size: 16384 }
    in Connection with peer=Client
    in release

  2024-09-06T09:15:57.680340Z DEBUG  received, frame: Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }
    in Connection with peer=Client
    in release

  2024-09-06T09:15:57.680472Z DEBUG  send, frame: GoAway { error_code: NO_ERROR, last_stream_id: StreamId(0) }
    in Connection with peer=Client
    in release

  2024-09-06T09:15:57.680492Z DEBUG  Connection::poll; connection error, error: GoAway(b"", NO_ERROR, Library)
    in Connection with peer=Client
    in release

  2024-09-06T09:15:57.681045Z ERROR  can't determine if package is published

Caused by:
    0: timeout while publishing mypackage
    1: failed fetching sparse metadata
    2: the request was not authorized

Error: can't determine if package is published

Caused by:
    0: timeout while publishing mypackage
    1: failed fetching sparse metadata
    2: the request was not authorized
```

It only works when additionally given the registry token on the commandline like: `release-plz release --backend gitlab --git-token "mygit-token-here" --registry myregistry --token "myregistry-token-here"`.

Log is more or less the same as above, but this time data is transferred and then cargo publish is called:

```log
  2024-09-06T09:25:48.637309Z DEBUG  received, frame: Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
    in Connection with peer=Client
    in release

>  2024-09-06T09:25:48.637365Z DEBUG  received, frame: Data { stream_id: StreamId(1), flags: (0x1: END_STREAM) }
>    in Connection with peer=Client
>    in release

  2024-09-06T09:25:48.638026Z DEBUG  send, frame: GoAway { error_code: NO_ERROR, last_stream_id: StreamId(0) }
    in Connection with peer=Client
    in release

  2024-09-06T09:25:48.638061Z DEBUG  Connection::poll; connection error, error: GoAway(b"", NO_ERROR, Library)
    in Connection with peer=Client
    in release

>  2024-09-06T09:25:48.638063Z DEBUG  cargo publish --color always --manifest-path /home/myuser/Projects/tests/mypackage/Cargo.toml --package mypackage --registry myregistry --token my-registry-token
>    in release

  2024-09-06T09:25:48.810904Z DEBUG  cargo stderr:     Updating `myregistry` index
warning: manifest has no description, license, license-file, documentation, homepage or repository.
See https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata for more info.
   Packaging mypackage v0.6.3 (/home/myuser/Projects/tests/mypackage)
   Verifying mypackage v0.6.3 (/home/myuser/Projects/tests/mypackage)
   Compiling mypackage v0.6.3 (/home/myuser/Projects/tests/mypackage/target/package/mypackage-0.6.3)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.11s
    Packaged 10 files, 9.1KiB (3.2KiB compressed)
   Uploading mypackage v0.6.3 (/home/myuser/Projects/tests/mypackage)
    Uploaded mypackage v0.6.3 to registry `myregistry`
note: waiting for `mypackage v0.6.3` to be available at registry `myregistry`.
You may press ctrl-c to skip waiting; the crate should be available shortly.
   Published mypackage v0.6.3 at registry `myregistry`
```

Looks like in `cargo.rs` `fn fetch_sparse_metadata()` would only work with a token set for authenticated registries.

---

From afar, it looks like there is not much of common ground in usage between release-pr/update(release) in this regard. Maybe I did just not understand it yet.

Making available both, `credentials.toml` and the `--token xy` on the commandline somehow works in my case, but not when one of them is missing.

This does not make a lot of sense from a usage standpoint. Also this enforces credentials injection in multiple ways for release-plz.

Would work on a PR, but I don't understand the intentions of the design and also have not the cargo/http/auth knowledge for this.

### PR DESCRIPTION
**Pull request by davidB**
tokens are read from:
- cli's argument `--token`
- environment variables (ala `cargo:token`)
- file `cargo/credentials.toml` (ala `cargo:token`)

Also registry + token is read for each package because:
- each package could be published to a different registry, 
- `--registry` and `--token` could be unspecified (in this case use info from `Cargo.toml` ,...)

FIX #1659

### CODE REVIEW

**Comment by davidB** [comment]
Possible "optimization", using a cache to store tokens to avoid read (env + file) for every package.

WDYT?

**Comment by mbodmer** [comment]
Thanks, this looks interesting and makes sense for me. Wouldn't it also make sense to cover the `release-pr` and `update` command the same way? Or would this actually also work already with your code?

**Comment by MarcoIeni** [comment]
> Possible "optimization", using a cache to store tokens to avoid read (env + file) for every package.

If you want PR welcome after we merge this one 👍

File: crates/release_plz_core/src/command/release.rs [hunk 1]
```diff
@@ -170,18 +170,22 @@ impl ReleaseRequest {
...
-                    .ok()
-                    .map(SecretString::new);
-                self.token.clone().or(env_token)
-            })
-            .or(self.token.clone())
+    fn find_registry_token(
+        &self,
+        registry: &Option<String>,
+    ) -> anyhow::Result<Option<secrecy::Secret<String>>> {
+        if self.registry == *registry {
```
Comment (MarcoIeni) [inline crates/release_plz_core/src/command/release.rs:177]: this is also true if both are None. Is it expected?
Also, can you document a bit this function?
Thanks

File: crates/release_plz_core/src/command/release.rs [hunk 2]
```diff
@@ -170,18 +170,22 @@ impl ReleaseRequest {
...
+            Ok(self
+                .token
+                .clone()
+                .or(cargo_utils::registry_token(&self.registry)?))
+        } else {
+            cargo_utils::registry_token(&self.registry)
+        }
+        .context(format!(
+            "can't retreive token for registry: {:?}",
```
Comment (MarcoIeni) [inline crates/release_plz_core/src/command/release.rs:186]: if registry is None this will print "can't retreive token for registry: None" which seems a bug

File: crates/release_plz_core/src/command/release.rs [hunk 3]
```diff
@@ -575,30 +580,32 @@ async fn should_release(
 fn registry_indexes(
     package: &Package,
     registry: Option<String>,
-) -> anyhow::Result<Vec<CargoIndex>> {
+) -> anyhow::Result<Vec<(Option<String>, CargoIndex)>> {
```
Comment (MarcoIeni) [inline crates/release_plz_core/src/command/release.rs:583]: could you turn the tuple into a struct? This type is already complex, thanks!

**Review by MarcoIeni — COMMENTED** [review]
looks good, just a small comments.

Also, it would be great if you could update the [docs](https://github.com/MarcoIeni/release-plz/tree/main/website/docs) as well 🙏

**Comment by davidB** [comment]
I didn't notice the issue with `update`. I searched only where token was used. I'll take a look.

File: crates/release_plz_core/src/command/release.rs (hunk 1 above)
Comment (davidB) [reply crates/release_plz_core/src/command/release.rs:177]: yes, it's expected. None means `crates.io` and I guess `--token` could be used also in this case and fallback to `crates:token`.

File: crates/release_plz_core/src/command/release.rs (hunk 2 above)
Comment (davidB) [reply crates/release_plz_core/src/command/release.rs:186]: yes I didn't know if we `None` or `crates.io`, idem about `Some('xxx')` or `'xxx'`. To have the info if value was defined or not.

File: crates/release_plz_core/src/command/release.rs (hunk 3 above)
Comment (davidB) [reply crates/release_plz_core/src/command/release.rs:583]: Sure, I was not sur if you prefer:
- the tuple
- a new struct which name? (as registry is a String or something else define in other crates)

```rust
struct CargoRegistry {
  name: Option<String>,
  index: CargoIndex,
}
```

**Comment by davidB** [comment]
I'll update the doc later this week.

File: crates/release_plz_core/src/command/release.rs (hunk 3 above)
Comment (MarcoIeni) [reply crates/release_plz_core/src/command/release.rs]: I like your `CargoRegistry` proposal 👍

I prefer the struct as it's more explicit

**Comment by davidB** [comment]
I was wrong. Maybe `update` need to be modify

**Comment by MarcoIeni** [comment]
no rush, take your time, we are all doing our best :)

File: crates/release_plz_core/src/registry_packages.rs [hunk 4]
```diff
@@ -62,17 +63,30 @@ pub fn get_registry_packages(
...
+            // HACK use the first registry in the `publish`
+            let mut registry_packages: Vec<Package> = vec![];
+            for (registry, packages) in &local_packages.iter().chunk_by(|p| {
+                registry.or_else(|| {
+                    p.publish
+                        .as_ref()
+                        .and_then(|p| p.first())
+                        .map(|x| x.as_str())
+                })
+            }) {
```
Comment (MarcoIeni) [inline crates/release_plz_core/src/registry_packages.rs:78]: can you extract what you are iterating on into a function or variable?
Maybe it's because it's quite late here, but I don't understand the use of chunk_by.

Maybe assigning a name to it and some comments will help

**Comment by MarcoIeni** [comment]
I hope you like how I refactored `release.rs` in https://github.com/MarcoIeni/release-plz/pull/1669/commits/5ec5b9d0b040e93ecc30fb71fb8d741f57d6240f :)

File: crates/release_plz_core/src/registry_packages.rs [hunk 5]
```diff
@@ -61,7 +61,7 @@ pub fn get_registry_packages(
                 })
                 .collect(),
         ),
-        Option::None => {
+        None => {
```
Comment (davidB) [inline crates/release_plz_core/src/registry_packages.rs:64]: I qualify None due to a warning on my editor ([rust-analyzer](https://doc.rust-lang.org/rustc/?search=non_snake_case)) with rust 1.81 (on my editor)

> Variable `None` should have snake_case name, e.g. `none`

Comment (MarcoIeni) [reply crates/release_plz_core/src/registry_packages.rs:64]: weird since None is not a variable.

**Review by MarcoIeni — APPROVED** [review]
this was an awesome contribution, thanks!!!!
