### PR TITLE
fix(#1487): don't close release PR on force-push

### LINKED ISSUE #1487: Release PR is closed when updating
## Bug description

In [this repository](https://github.com/mamba-org/rattler) Im making extensive use of release-plz. I absolute love it. However, for a little while now it appears that when release-plz _updates_ the release PR it immediately closes it. I cannot find anything in the logs that suggests that release-plz is doing this. 

- Would you like to work on a fix? [n]

## To Reproduce

I dont have isolated steps to reproduce this issue but I can show steps that exhibit this behavior in the aformentioned repository.

If you take a look at all the workflow runs of release-plz for the main branch: https://github.com/mamba-org/rattler/actions/workflows/release-rust.yaml

You can see that when PR 666 was merged release-plz create a new release PR. This is the workflow run: https://github.com/mamba-org/rattler/actions/runs/9186703934/job/25262873395

Release-plz notices changes in some of the crates and opens a release PR as can be seen in the logs:

```
2024-05-22T07:03:29.666711Z  INFO  opened pr: https://github.com/mamba-org/rattler/pull/668
    in open_pr
    in release_pr

release_pr_output: {"prs":[{"base_branch":"main","head_branch":"release-plz-2024-05-22T07-03-26Z","html_url":"https://github.com/mamba-org/rattler/pull/668","number":668}]}
```

However the [next run of release-plz](https://github.com/mamba-org/rattler/actions/runs/9193700451/job/25285384837) (the release pr was not merged), seems to update the release PR.

```

  2024-05-22T15:06:28.471231Z  INFO  updated pr https://github.com/mamba-org/rattler/pull/668
    in release_pr

release_pr_output: {"prs":[{"base_branch":"main","head_branch":"release-plz-2024-05-22T07-03-26Z","html_url":"https://github.com/mamba-org/rattler/pull/668","number":668}]}
```

Indeed the [release PR](https://github.com/mamba-org/rattler/pull/668) also includes the changes of the last merged PR. However, it was also immediately closed. Reading the logs I can see no indication as to why this would happen.

## Expected behavior

I would expect the release PR to not be closed. Manually reopening and merging the PR seems to be the workaround.

## Environment

- release-plz version: 0.3.68

### PR DESCRIPTION
**Pull request by zvolin**
Fixes #1487 

Force pushing a branch that links to an open PR with the content of a base branch automatically closes it. To prevent that we create a new temporary branch for release, commit there and then force push original one.

### CODE REVIEW

File: crates/release_plz_core/src/command/release_pr.rs [hunk 1]
```diff
@@ -311,9 +311,49 @@ async fn github_force_push(
...
+        let branch = Self { name, repository };
+        Ok(branch)
+    }
+}
+
+impl Drop for TmpBranch<'_> {
+    fn drop(&mut self) {
+        if let Err(e) = self.repository.delete_branch_in_remote(&self.name) {
+            tracing::error!("cannot delete branch {}: {:?}", self.name, e);
+        }
```
Comment (MarcoIeni) [inline crates/release_plz_core/src/command/release_pr.rs:355]: Should we also delete the branch from the local repository?
I know this command is run in a temporary directory, but just to clean up things correctly, in case we reuse this code somewhere else, or if in the future we change the "temporary directory" strategy

Comment (zvolin) [reply crates/release_plz_core/src/command/release_pr.rs:355]: I was thinking about it. Committing through graphql leaves all the changes uncommitted locally and I wasn't sure if it's okay to remove everything, even untracked files blindly? They can conflict when running `git checkout ...`, and we must switch the branch to delete this temporary one.
Another way would be replacing the `git fetch ...` with `git pull --force ...` so that it would overwrite already committed content making checkout easier.

I decided to leave it like so to not increase complexity however it's definitely an option.

Comment (MarcoIeni) [reply crates/release_plz_core/src/command/release_pr.rs:355]: > I decided to leave it like so to not increase complexity however it's definitely an option.

Sounds good 👍
